import type {
  Reporter,
  FullConfig,
  Suite,
  TestCase,
  TestResult,
  FullResult,
} from '@playwright/test/reporter';
import { writeFileSync } from 'fs';
import path from 'path';

/**
 * TARS Mission Control — a custom Playwright reporter that turns a raw test run
 * into quality intelligence.
 *
 * On every run it autonomously computes the signals a principal SDET would look
 * for first — pass rate, flake (tests that only went green on retry), the
 * slowest paths, and a breakdown by project and tag — then writes a Markdown
 * "mission control" brief (tars-report.md) and prints a compact console summary.
 *
 * Hard rule: a reporter must never break the run. Everything here is defensive
 * and wrapped; on any internal error it degrades silently rather than failing
 * the suite.
 */

interface TestRecord {
  title: string;
  project: string;
  tags: string[];
  status: TestResult['status'];
  outcome: ReturnType<TestCase['outcome']>;
  durationMs: number;
  retries: number;
}

const REPORT_FILE = 'tars-report.md';

export default class TarsReporter implements Reporter {
  private records: TestRecord[] = [];
  private startedAt = 0;

  printsToStdio(): boolean {
    return true;
  }

  onBegin(_config: FullConfig, _suite: Suite): void {
    this.startedAt = Date.now();
  }

  onTestEnd(test: TestCase, result: TestResult): void {
    try {
      this.records.push({
        title: test.title,
        project: test.titlePath()[1] || 'unknown',
        tags: test.tags ?? [],
        status: result.status,
        outcome: test.outcome(),
        durationMs: result.duration,
        retries: result.retry,
      });
    } catch {
      // Never let collection break a run.
    }
  }

  async onEnd(result: FullResult): Promise<void> {
    try {
      const brief = this.buildBrief(result.status);
      writeFileSync(path.join(process.cwd(), REPORT_FILE), brief.markdown);

      console.log(brief.console);
    } catch {
      // Degrade silently — the run result itself is unaffected.
    }
  }

  private buildBrief(runStatus: FullResult['status']): {
    markdown: string;
    console: string;
  } {
    const total = this.records.length;
    const passed = this.records.filter((r) => r.outcome === 'expected').length;
    const failed = this.records.filter(
      (r) => r.outcome === 'unexpected',
    ).length;
    const flaky = this.records.filter((r) => r.outcome === 'flaky');
    const skipped = this.records.filter((r) => r.outcome === 'skipped').length;
    const executed = total - skipped;
    const passRate = executed ? ((passed / executed) * 100).toFixed(1) : '0.0';
    const flakeRate = executed
      ? ((flaky.length / executed) * 100).toFixed(2)
      : '0.00';
    const wallMs = Date.now() - this.startedAt;

    const slowest = [...this.records]
      .sort((a, b) => b.durationMs - a.durationMs)
      .slice(0, 5);

    const byProject = this.groupCounts((r) => r.project);
    const byTag = this.groupCounts((r) =>
      r.tags.length ? r.tags.join(' ') : '(untagged)',
    );

    const verdict =
      runStatus === 'passed'
        ? '🟢 ALL SYSTEMS GREEN'
        : runStatus === 'failed'
          ? '🔴 ATTENTION REQUIRED'
          : `⚠️  ${runStatus.toUpperCase()}`;

    const md = [
      '# 🤖 TARS — Mission Control Brief',
      '',
      `**Verdict:** ${verdict}`,
      '',
      '## Signals',
      '',
      '| Metric | Value |',
      '| --- | --- |',
      `| Pass rate | ${passRate}% (${passed}/${executed}) |`,
      `| Flake rate | ${flakeRate}% (${flaky.length} flaky) |`,
      `| Failed | ${failed} |`,
      `| Skipped | ${skipped} |`,
      `| Total | ${total} |`,
      `| Wall time | ${fmtMs(wallMs)} |`,
      '',
      '## By project',
      '',
      this.table('Project', byProject),
      '',
      '## By tag',
      '',
      this.table('Tag', byTag),
      '',
      '## Slowest paths',
      '',
      '| Test | Project | Duration |',
      '| --- | --- | --- |',
      ...slowest.map(
        (r) => `| ${r.title} | ${r.project} | ${fmtMs(r.durationMs)} |`,
      ),
      '',
      ...(flaky.length
        ? [
            '## ⚠️ Flake watch',
            '',
            'These passed only on retry — quarantine candidates:',
            '',
            ...flaky.map((r) => `- \`${r.project}\` › ${r.title}`),
            '',
          ]
        : []),
      '_Generated by TARS Mission Control._',
      '',
    ].join('\n');

    const con = [
      '',
      '┌─ 🤖 TARS Mission Control ─────────────────────────────',
      `│ ${verdict}`,
      `│ Pass ${passRate}% (${passed}/${executed})  ·  Flake ${flakeRate}%  ·  Fail ${failed}  ·  ${fmtMs(wallMs)}`,
      `│ Brief written to ${REPORT_FILE}`,
      '└───────────────────────────────────────────────────────',
    ].join('\n');

    return { markdown: md, console: con };
  }

  private groupCounts(key: (r: TestRecord) => string): Map<string, number> {
    const map = new Map<string, number>();
    for (const r of this.records) {
      map.set(key(r), (map.get(key(r)) ?? 0) + 1);
    }
    return map;
  }

  private table(label: string, counts: Map<string, number>): string {
    const rows = [...counts.entries()]
      .sort((a, b) => b[1] - a[1])
      .map(([k, n]) => `| ${k} | ${n} |`);
    return [`| ${label} | Tests |`, '| --- | --- |', ...rows].join('\n');
  }
}

function fmtMs(ms: number): string {
  if (ms < 1000) return `${ms}ms`;
  const s = ms / 1000;
  if (s < 60) return `${s.toFixed(1)}s`;
  const m = Math.floor(s / 60);
  return `${m}m ${Math.round(s % 60)}s`;
}
